version: '3.8'

services:
  photobooth:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./Photos:/app/Photos
      - ./Output_ReadyToPrint:/app/Output_ReadyToPrint
      - ./Archive:/app/Archive
    env_file:
      - .env
    restart: always
